### ISSUE TITLE
react-scripts

### ISSUE THREAD

**Issue by MohammedAlbalaawi** [vvHacker007/Portfolio#2]
Hi, after cloning the project and run the command `npm start` I got this error 
`'react-scripts' is not recognized as an internal or external command, operable program or batch file.`
I tried some ways the solve it, but it doesn't not work, can you help me with this problem, please.

**Comment by vvHacker007** [comment]
It is an npm error that says you don't have react installed in your node_modules folder. I believe a simple `npm i` should do the work.
